-- AlterTable
ALTER TABLE `case_progress_histories` MODIFY `from_progress` ENUM('NOT_SELECTED', 'REGISTRATION_CREATED', 'REGISTRATION_COMPLETED', 'UNDER_REVIEW', 'APPROVED', 'CARD_ISSUED', 'CARD_ACTIVATED', 'COMPLETED') NULL,
    MODIFY `to_progress` ENUM('NOT_SELECTED', 'REGISTRATION_CREATED', 'REGISTRATION_COMPLETED', 'UNDER_REVIEW', 'APPROVED', 'CARD_ISSUED', 'CARD_ACTIVATED', 'COMPLETED') NOT NULL;

-- AlterTable
ALTER TABLE `customer_cases` MODIFY `progress` ENUM('NOT_SELECTED', 'REGISTRATION_CREATED', 'REGISTRATION_COMPLETED', 'UNDER_REVIEW', 'APPROVED', 'CARD_ISSUED', 'CARD_ACTIVATED', 'COMPLETED') NOT NULL DEFAULT 'NOT_SELECTED';
